triplet_maps = {
    "cholect50": {
        "ivt": {
            "0": "grasper,dissect,cystic_plate",
            "1": "grasper,dissect,gallbladder",
            "2": "grasper,dissect,omentum",
            "3": "grasper,grasp,cystic_artery",
            "4": "grasper,grasp,cystic_duct",
            "5": "grasper,grasp,cystic_pedicle",
            "6": "grasper,grasp,cystic_plate",
            "7": "grasper,grasp,gallbladder",
            "8": "grasper,grasp,gut",
            "9": "grasper,grasp,liver",
            "10": "grasper,grasp,omentum",
            "11": "grasper,grasp,peritoneum",
            "12": "grasper,grasp,specimen_bag",
            "13": "grasper,pack,gallbladder",
            "14": "grasper,retract,cystic_duct",
            "15": "grasper,retract,cystic_pedicle",
            "16": "grasper,retract,cystic_plate",
            "17": "grasper,retract,gallbladder",
            "18": "grasper,retract,gut",
            "19": "grasper,retract,liver",
            "20": "grasper,retract,omentum",
            "21": "grasper,retract,peritoneum",
            "22": "bipolar,coagulate,abdominal_wall_cavity",
            "23": "bipolar,coagulate,blood_vessel",
            "24": "bipolar,coagulate,cystic_artery",
            "25": "bipolar,coagulate,cystic_duct",
            "26": "bipolar,coagulate,cystic_pedicle",
            "27": "bipolar,coagulate,cystic_plate",
            "28": "bipolar,coagulate,gallbladder",
            "29": "bipolar,coagulate,liver",
            "30": "bipolar,coagulate,omentum",
            "31": "bipolar,coagulate,peritoneum",
            "32": "bipolar,dissect,adhesion",
            "33": "bipolar,dissect,cystic_artery",
            "34": "bipolar,dissect,cystic_duct",
            "35": "bipolar,dissect,cystic_plate",
            "36": "bipolar,dissect,gallbladder",
            "37": "bipolar,dissect,omentum",
            "38": "bipolar,grasp,cystic_plate",
            "39": "bipolar,grasp,liver",
            "40": "bipolar,grasp,specimen_bag",
            "41": "bipolar,retract,cystic_duct",
            "42": "bipolar,retract,cystic_pedicle",
            "43": "bipolar,retract,gallbladder",
            "44": "bipolar,retract,liver",
            "45": "bipolar,retract,omentum",
            "46": "hook,coagulate,blood_vessel",
            "47": "hook,coagulate,cystic_artery",
            "48": "hook,coagulate,cystic_duct",
            "49": "hook,coagulate,cystic_pedicle",
            "50": "hook,coagulate,cystic_plate",
            "51": "hook,coagulate,gallbladder",
            "52": "hook,coagulate,liver",
            "53": "hook,coagulate,omentum",
            "54": "hook,cut,blood_vessel",
            "55": "hook,cut,peritoneum",
            "56": "hook,dissect,blood_vessel",
            "57": "hook,dissect,cystic_artery",
            "58": "hook,dissect,cystic_duct",
            "59": "hook,dissect,cystic_plate",
            "60": "hook,dissect,gallbladder",
            "61": "hook,dissect,omentum",
            "62": "hook,dissect,peritoneum",
            "63": "hook,retract,gallbladder",
            "64": "hook,retract,liver",
            "65": "scissors,coagulate,omentum",
            "66": "scissors,cut,adhesion",
            "67": "scissors,cut,blood_vessel",
            "68": "scissors,cut,cystic_artery",
            "69": "scissors,cut,cystic_duct",
            "70": "scissors,cut,cystic_plate",
            "71": "scissors,cut,liver",
            "72": "scissors,cut,omentum",
            "73": "scissors,cut,peritoneum",
            "74": "scissors,dissect,cystic_plate",
            "75": "scissors,dissect,gallbladder",
            "76": "scissors,dissect,omentum",
            "77": "clipper,clip,blood_vessel",
            "78": "clipper,clip,cystic_artery",
            "79": "clipper,clip,cystic_duct",
            "80": "clipper,clip,cystic_pedicle",
            "81": "clipper,clip,cystic_plate",
            "82": "irrigator,aspirate,fluid",
            "83": "irrigator,dissect,cystic_duct",
            "84": "irrigator,dissect,cystic_pedicle",
            "85": "irrigator,dissect,cystic_plate",
            "86": "irrigator,dissect,gallbladder",
            "87": "irrigator,dissect,omentum",
            "88": "irrigator,irrigate,abdominal_wall_cavity",
            "89": "irrigator,irrigate,cystic_pedicle",
            "90": "irrigator,irrigate,liver",
            "91": "irrigator,retract,gallbladder",
            "92": "irrigator,retract,liver",
            "93": "irrigator,retract,omentum",
            "94": "grasper,null_verb,null_target",
            "95": "bipolar,null_verb,null_target",
            "96": "hook,null_verb,null_target",
            "97": "scissors,null_verb,null_target",
            "98": "clipper,null_verb,null_target",
            "99": "irrigator,null_verb,null_target"
        },
        "i": {
            "0": "grasper",
            "1": "bipolar",
            "2": "hook",
            "3": "scissors",
            "4": "clipper",
            "5": "irrigator"
        },
        "v": {
            "0": "grasp",
            "1": "retract",
            "2": "dissect",
            "3": "coagulate",
            "4": "clip",
            "5": "cut",
            "6": "aspirate",
            "7": "irrigate",
            "8": "pack",
            "9": "null_verb"
        },
        "t": {
            "0": "gallbladder",
            "1": "cystic_plate",
            "2": "cystic_duct",
            "3": "cystic_artery",
            "4": "cystic_pedicle",
            "5": "blood_vessel",
            "6": "fluid",
            "7": "abdominal_wall_cavity",
            "8": "liver",
            "9": "adhesion",
            "10": "omentum",
            "11": "peritoneum",
            "12": "gut",
            "13": "specimen_bag",
            "14": "null_target"
        },
        "iv": {
            "0": "grasper,grasp",
            "1": "grasper,retract",
            "2": "grasper,dissect",
            "3": "grasper,pack",
            "4": "grasper,null_verb",
            "5": "bipolar,grasp",
            "6": "bipolar,retract",
            "7": "bipolar,dissect",
            "8": "bipolar,coagulate",
            "9": "bipolar,null_verb",
            "10": "hook,retract",
            "11": "hook,dissect",
            "12": "hook,coagulate",
            "13": "hook,cut",
            "14": "hook,null_verb",
            "15": "scissors,dissect",
            "16": "scissors,coagulate",
            "17": "scissors,cut",
            "18": "scissors,null_verb",
            "19": "clipper,clip",
            "20": "clipper,null_verb",
            "21": "irrigator,retract",
            "22": "irrigator,dissect",
            "23": "irrigator,aspirate",
            "24": "irrigator,irrigate",
            "25": "irrigator,null_verb"
        },
        "it": {
            "0": "grasper,gallbladder",
            "1": "grasper,cystic_plate",
            "2": "grasper,cystic_duct",
            "3": "grasper,cystic_artery",
            "4": "grasper,cystic_pedicle",
            "5": "grasper,liver",
            "6": "grasper,omentum",
            "7": "grasper,peritoneum",
            "8": "grasper,gut",
            "9": "grasper,specimen_bag",
            "10": "grasper,null_target",
            "11": "bipolar,gallbladder",
            "12": "bipolar,cystic_plate",
            "13": "bipolar,cystic_duct",
            "14": "bipolar,cystic_artery",
            "15": "bipolar,cystic_pedicle",
            "16": "bipolar,blood_vessel",
            "17": "bipolar,abdominal_wall_cavity",
            "18": "bipolar,liver",
            "19": "bipolar,adhesion",
            "20": "bipolar,omentum",
            "21": "bipolar,peritoneum",
            "22": "bipolar,specimen_bag",
            "23": "bipolar,null_target",
            "24": "hook,gallbladder",
            "25": "hook,cystic_plate",
            "26": "hook,cystic_duct",
            "27": "hook,cystic_artery",
            "28": "hook,cystic_pedicle",
            "29": "hook,blood_vessel",
            "30": "hook,liver",
            "31": "hook,omentum",
            "32": "hook,peritoneum",
            "33": "hook,null_target",
            "34": "scissors,gallbladder",
            "35": "scissors,cystic_plate",
            "36": "scissors,cystic_duct",
            "37": "scissors,cystic_artery",
            "38": "scissors,blood_vessel",
            "39": "scissors,liver",
            "40": "scissors,adhesion",
            "41": "scissors,omentum",
            "42": "scissors,peritoneum",
            "43": "scissors,null_target",
            "44": "clipper,cystic_plate",
            "45": "clipper,cystic_duct",
            "46": "clipper,cystic_artery",
            "47": "clipper,cystic_pedicle",
            "48": "clipper,blood_vessel",
            "49": "clipper,null_target",
            "50": "irrigator,gallbladder",
            "51": "irrigator,cystic_plate",
            "52": "irrigator,cystic_duct",
            "53": "irrigator,cystic_pedicle",
            "54": "irrigator,fluid",
            "55": "irrigator,abdominal_wall_cavity",
            "56": "irrigator,liver",
            "57": "irrigator,omentum",
            "58": "irrigator,null_target"
        },
        "p": {
            "0": "preparation",
            "1": "carlot-triangle-dissection",
            "2": "clipping-and-cutting",
            "3": "gallbladder-dissection",
            "4": "gallbladder-packaging",
            "5": "cleaning-and-coagulation",
            "6": "gallbladder-extraction"
        },
        "component_maps": [
                [ 0,  0,  2,  1,  2,  1],
                [ 1,  0,  2,  0,  2,  0],
                [ 2,  0,  2, 10,  2, 10],
                [ 3,  0,  0,  3,  0,  3],
                [ 4,  0,  0,  2,  0,  2],
                [ 5,  0,  0,  4,  0,  4],
                [ 6,  0,  0,  1,  0,  1],
                [ 7,  0,  0,  0,  0,  0],
                [ 8,  0,  0, 12,  0, 12],
                [ 9,  0,  0,  8,  0,  8],
                [10,  0,  0, 10,  0, 10],
                [11,  0,  0, 11,  0, 11],
                [12,  0,  0, 13,  0, 13],
                [13,  0,  8,  0,  8,  0],
                [14,  0,  1,  2,  1,  2],
                [15,  0,  1,  4,  1,  4],
                [16,  0,  1,  1,  1,  1],
                [17,  0,  1,  0,  1,  0],
                [18,  0,  1, 12,  1, 12],
                [19,  0,  1,  8,  1,  8],
                [20,  0,  1, 10,  1, 10],
                [21,  0,  1, 11,  1, 11],
                [22,  1,  3,  7, 13, 22],
                [23,  1,  3,  5, 13, 20],
                [24,  1,  3,  3, 13, 18],
                [25,  1,  3,  2, 13, 17],
                [26,  1,  3,  4, 13, 19],
                [27,  1,  3,  1, 13, 16],
                [28,  1,  3,  0, 13, 15],
                [29,  1,  3,  8, 13, 23],
                [30,  1,  3, 10, 13, 25],
                [31,  1,  3, 11, 13, 26],
                [32,  1,  2,  9, 12, 24],
                [33,  1,  2,  3, 12, 18],
                [34,  1,  2,  2, 12, 17],
                [35,  1,  2,  1, 12, 16],
                [36,  1,  2,  0, 12, 15],
                [37,  1,  2, 10, 12, 25],
                [38,  1,  0,  1, 10, 16],
                [39,  1,  0,  8, 10, 23],
                [40,  1,  0, 13, 10, 28],
                [41,  1,  1,  2, 11, 17],
                [42,  1,  1,  4, 11, 19],
                [43,  1,  1,  0, 11, 15],
                [44,  1,  1,  8, 11, 23],
                [45,  1,  1, 10, 11, 25],
                [46,  2,  3,  5, 23, 35],
                [47,  2,  3,  3, 23, 33],
                [48,  2,  3,  2, 23, 32],
                [49,  2,  3,  4, 23, 34],
                [50,  2,  3,  1, 23, 31],
                [51,  2,  3,  0, 23, 30],
                [52,  2,  3,  8, 23, 38],
                [53,  2,  3, 10, 23, 40],
                [54,  2,  5,  5, 25, 35],
                [55,  2,  5, 11, 25, 41],
                [56,  2,  2,  5, 22, 35],
                [57,  2,  2,  3, 22, 33],
                [58,  2,  2,  2, 22, 32],
                [59,  2,  2,  1, 22, 31],
                [60,  2,  2,  0, 22, 30],
                [61,  2,  2, 10, 22, 40],
                [62,  2,  2, 11, 22, 41],
                [63,  2,  1,  0, 21, 30],
                [64,  2,  1,  8, 21, 38],
                [65,  3,  3, 10, 33, 55],
                [66,  3,  5,  9, 35, 54],
                [67,  3,  5,  5, 35, 50],
                [68,  3,  5,  3, 35, 48],
                [69,  3,  5,  2, 35, 47],
                [70,  3,  5,  1, 35, 46],
                [71,  3,  5,  8, 35, 53],
                [72,  3,  5, 10, 35, 55],
                [73,  3,  5, 11, 35, 56],
                [74,  3,  2,  1, 32, 46],
                [75,  3,  2,  0, 32, 45],
                [76,  3,  2, 10, 32, 55],
                [77,  4,  4,  5, 44, 65],
                [78,  4,  4,  3, 44, 63],
                [79,  4,  4,  2, 44, 62],
                [80,  4,  4,  4, 44, 64],
                [81,  4,  4,  1, 44, 61],
                [82,  5,  6,  6, 56, 81],
                [83,  5,  2,  2, 52, 77],
                [84,  5,  2,  4, 52, 79],
                [85,  5,  2,  1, 52, 76],
                [86,  5,  2,  0, 52, 75],
                [87,  5,  2, 10, 52, 85],
                [88,  5,  7,  7, 57, 82],
                [89,  5,  7,  4, 57, 79],
                [90,  5,  7,  8, 57, 83],
                [91,  5,  1,  0, 51, 75],
                [92,  5,  1,  8, 51, 83],
                [93,  5,  1, 10, 51, 85],
                [94,  0,  9, 14,  9, 14],
                [95,  1,  9, 14, 19, 29],
                [96,  2,  9, 14, 29, 44],
                [97,  3,  9, 14, 39, 59],
                [98,  4,  9, 14, 49, 74],
                [99,  5,  9, 14, 59, 89]
                ]
    },
    "multibypasst40": {
        "ivt": {
            "0": "grasper,grasp,small_bowel",
            "1": "grasper,grasp,stomach",
            "2": "grasper,grasp,thread",
            "3": "grasper,grasp,omentum",
            "4": "grasper,grasp,liver",
            "5": "grasper,grasp,needle",
            "6": "grasper,grasp,mesentery",
            "7": "grasper,grasp,colon",
            "8": "grasper,retract,small_bowel",
            "9": "grasper,retract,stomach",
            "10": "grasper,retract,omentum",
            "11": "grasper,retract,liver",
            "12": "grasper,retract,mesentery",
            "13": "grasper,retract,sponge",
            "14": "grasper,retract,colon",
            "15": "grasper,dissect,small_bowel",
            "16": "grasper,dissect,stomach",
            "17": "grasper,dissect,omentum",
            "18": "grasper,dissect,mesentery",
            "19": "grasper,suture,small_bowel",
            "20": "grasper,suture,mesentery",
            "21": "grasper,suture,small_bowel_stomach_anastomosis",
            "22": "grasper,suture,small_bowel_anastomosis",
            "23": "stapler,grasp,small_bowel",
            "24": "stapler,grasp,stomach",
            "25": "stapler,grasp,small_bowel_stomach_anastomosis",
            "26": "stapler,grasp,small_bowel_anastomosis",
            "27": "stapler,retract,stomach",
            "28": "stapler,staple,small_bowel",
            "29": "stapler,staple,stomach",
            "30": "stapler,staple,small_bowel_stomach_anastomosis",
            "31": "stapler,staple,small_bowel_anastomosis",
            "32": "electric_hook,dissect,small_bowel",
            "33": "electric_hook,dissect,stomach",
            "34": "electric_hook,dissect,omentum",
            "35": "electric_hook,coagulate,spleen",
            "36": "right_angle_dissector,grasp,stomach",
            "37": "right_angle_dissector,dissect,small_bowel",
            "38": "right_angle_dissector,dissect,stomach",
            "39": "energy_device,grasp,omentum",
            "40": "energy_device,retract,small_bowel",
            "41": "energy_device,retract,stomach",
            "42": "energy_device,retract,omentum",
            "43": "energy_device,dissect,small_bowel",
            "44": "energy_device,dissect,stomach",
            "45": "energy_device,dissect,omentum",
            "46": "energy_device,dissect,mesentery",
            "47": "energy_device,cut,small_bowel",
            "48": "energy_device,cut,stomach",
            "49": "energy_device,cut,omentum",
            "50": "energy_device,cut,mesentery",
            "51": "energy_device,cut,adhesion",
            "52": "energy_device,coagulate,stomach",
            "53": "energy_device,coagulate,omentum",
            "54": "irrigator_aspirator,retract,small_bowel",
            "55": "irrigator_aspirator,retract,stomach",
            "56": "irrigator_aspirator,aspirate,fluid",
            "57": "irrigator_aspirator,irrigate,fluid",
            "58": "needle_driver,grasp,thread",
            "59": "needle_driver,grasp,needle",
            "60": "needle_driver,retract,small_bowel",
            "61": "needle_driver,suture,small_bowel",
            "62": "needle_driver,suture,mesentery",
            "63": "needle_driver,suture,small_bowel_stomach_anastomosis",
            "64": "needle_driver,suture,small_bowel_anastomosis",
            "65": "clipper,clip,small_bowel",
            "66": "clipper,clip,stomach",
            "67": "bipolar_forceps,grasp,sponge",
            "68": "bipolar_forceps,coagulate,stomach",
            "69": "suture_passer,pass,thread",
            "70": "swab_forceps,retract,small_bowel",
            "71": "swab_forceps,retract,liver",
            "72": "swab_forceps,clean,small_bowel",
            "73": "swab_forceps,clean,stomach",
            "74": "gauze,clean,stomach",
            "75": "grasper,null_verb,null_target",
            "76": "stapler,null_verb,null_target",
            "77": "electric_hook,null_verb,null_target",
            "78": "right_angle_dissector,null_verb,null_target",
            "79": "energy_device,null_verb,null_target",
            "80": "irrigator_aspirator,null_verb,null_target",
            "81": "needle_driver,null_verb,null_target",
            "82": "clipper,null_verb,null_target",
            "83": "bipolar_forceps,null_verb,null_target",
            "84": "swab_forceps,null_verb,null_target",
            },
        "i": {
            "0": "grasper",
            "1": "stapler",
            "2": "electric_hook",
            "3": "right_angle_dissector",
            "4": "energy_device",
            "5": "irrigator_aspirator",
            "6": "needle_driver",
            "7": "clipper",
            "8": "bipolar_forceps",
            "9": "suture_passer",
            "10": "swab_forceps",
            "11": "gauze",
            },
        "v": {
            "0": "grasp",
            "1": "retract",
            "2": "dissect",
            "3": "suture",
            "4": "staple",
            "5": "coagulate",
            "6": "cut",
            "7": "aspirate",
            "8": "irrigate",
            "9": "clip",
            "10": "pass",
            "11": "clean",
            "12": "null_verb",
            },
        "t": {
            "0": "small_bowel",
            "1": "stomach",
            "2": "thread",
            "3": "omentum",
            "4": "liver",
            "5": "needle",
            "6": "mesentery",
            "7": "colon",
            "8": "sponge",
            "9": "small_bowel_stomach_anastomosis",
            "10": "small_bowel_anastomosis",
            "11": "spleen",
            "12": "adhesion",
            "13": "fluid",
            "14": "null_target",
            },
        "p": {
            "0": "preparation",
            "1": "gastric_pouch_creation",
            "2": "omentum_division",
            "3": "gastrojejunal_anastomosis",
            "4": "anastomosis_test",
            "5": "jejunal_separation",
            "6": "closure_petersen_space",
            "7": "jejunojejunal_anastomosis",
            "8": "closure_mesenteric_defect",
            "9": "cleaning_coagulation",
            "10": "disassembling",
            "11": "other_intervention"
        },
        "component_maps": [
            [0, 0, 0, 0, 0, 0],
            [1, 0, 0, 1, 0, 1],
            [2, 0, 0, 2, 0, 2],
            [3, 0, 0, 3, 0, 3],
            [4, 0, 0, 4, 0, 4],
            [5, 0, 0, 5, 0, 5],
            [6, 0, 0, 6, 0, 6],
            [7, 0, 0, 7, 0, 7],
            [8, 0, 1, 0, 1, 0],
            [9, 0, 1, 1, 1, 1],
            [10, 0, 1, 3, 1, 3],
            [11, 0, 1, 4, 1, 4],
            [12, 0, 1, 6, 1, 6],
            [13, 0, 1, 8, 1, 8],
            [14, 0, 1, 7, 1, 7],
            [15, 0, 2, 0, 2, 0],
            [16, 0, 2, 1, 2, 1],
            [17, 0, 2, 3, 2, 3],
            [18, 0, 2, 6, 2, 6],
            [19, 0, 3, 0, 3, 0],
            [20, 0, 3, 6, 3, 6],
            [21, 0, 3, 9, 3, 9],
            [22, 0, 3, 10, 3, 10],
            [23, 1, 0, 0, 4, 11],
            [24, 1, 0, 1, 4, 12],
            [25, 1, 0, 9, 4, 13],
            [26, 1, 0, 10, 4, 14],
            [27, 1, 1, 1, 5, 12],
            [28, 1, 4, 0, 6, 11],
            [29, 1, 4, 1, 6, 12],
            [30, 1, 4, 9, 6, 13],
            [31, 1, 4, 10, 6, 14],
            [32, 2, 2, 0, 7, 15],
            [33, 2, 2, 1, 7, 16],
            [34, 2, 2, 3, 7, 17],
            [35, 2, 5, 11, 8, 18],
            [36, 3, 0, 1, 9, 19],
            [37, 3, 2, 0, 10, 20],
            [38, 3, 2, 1, 10, 19],
            [39, 4, 0, 3, 11, 21],
            [40, 4, 1, 0, 12, 22],
            [41, 4, 1, 1, 12, 23],
            [42, 4, 1, 3, 12, 21],
            [43, 4, 2, 0, 13, 22],
            [44, 4, 2, 1, 13, 23],
            [45, 4, 2, 3, 13, 21],
            [46, 4, 2, 6, 13, 24],
            [47, 4, 6, 0, 14, 22],
            [48, 4, 6, 1, 14, 23],
            [49, 4, 6, 3, 14, 21],
            [50, 4, 6, 6, 14, 24],
            [51, 4, 6, 12, 14, 25],
            [52, 4, 5, 1, 15, 23],
            [53, 4, 5, 3, 15, 21],
            [54, 5, 1, 0, 16, 26],
            [55, 5, 1, 1, 16, 27],
            [56, 5, 7, 13, 17, 28],
            [57, 5, 8, 13, 18, 28],
            [58, 6, 0, 2, 19, 29],
            [59, 6, 0, 5, 19, 30],
            [60, 6, 1, 0, 20, 31],
            [61, 6, 3, 0, 21, 31],
            [62, 6, 3, 6, 21, 32],
            [63, 6, 3, 9, 21, 33],
            [64, 6, 3, 10, 21, 34],
            [65, 7, 9, 0, 22, 35],
            [66, 7, 9, 1, 22, 36],
            [67, 8, 0, 8, 23, 37],
            [68, 8, 5, 1, 24, 38],
            [69, 9, 10, 2, 25, 39],
            [70, 10, 1, 0, 26, 40],
            [71, 10, 1, 4, 26, 41],
            [72, 10, 11, 0, 27, 40],
            [73, 10, 11, 1, 27, 42],
            [74, 11, 11, 1, 28, 43],
            [75, 0, 12, 14, 29, 44],
            [76, 1, 12, 14, 30, 45],
            [77, 2, 12, 14, 31, 46],
            [78, 3, 12, 14, 32, 47],
            [79, 4, 12, 14, 33, 48],
            [80, 5, 12, 14, 34, 49],
            [81, 6, 12, 14, 35, 50],
            [82, 7, 12, 14, 36, 51],
            [83, 8, 12, 14, 37, 52],
            [84, 10, 12, 14, 38, 53]
        ]
    }
}